### ISSUE TITLE
Update docs to v1 API

### ISSUE THREAD

**Issue by restrry** [redux-saga/redux-saga#1478]
Api changes that should be reflected in docs. Also would be nice to add examples, especially for new effect
- [x] put.resolve —> putResolve (#1492)
- [x] task.done —> task.toPromise (#1456)
- [x] take.maybe —> takeMaybe (#1492)
- [x] `delay` as effect (#1492)
- [x] `takeLeading` effect (#1492)
- [x] `retry` effect
- [x] `debounce` effect (#1492)
- [x] eventChannel emitting errors (#1519)
- [x] babel plugin usage example (https://github.com/redux-saga/redux-saga/pull/1546)
- [x] list of library changes from 0.x to 1.0 (https://github.com/redux-saga/redux-saga/pull/1613)
- [x] upgrade path from 0.x to 1.0 (https://github.com/redux-saga/redux-saga/pull/1613)
- [x] update examples in docs to new api (https://github.com/redux-saga/redux-saga/pull/1636)
- [x] remove logError https://github.com/redux-saga/redux-saga/pull/1658 (https://github.com/redux-saga/redux-saga/pull/1700)
- [x] change sagaStack passing https://github.com/redux-saga/redux-saga/pull/1695 (https://github.com/redux-saga/redux-saga/pull/1700)

**Comment by Slapbox** [comment]
Is there an ETA for stable v1.0? A month? 6 months?

Some rough estimate, however rough, would be really helpful. Sorry, I know a little off topic, but I don't want to clutter the issues.

Thanks to everyone who works on this incredible project.

**Comment by Andarist** [comment]
@Slapbox no rough estimate, probably few months (2-3?), we are moving quite slowly, although things got a little bit faster lately

**Comment by Andarist** [comment]
Keep in mind that v1 will be just a small evolution and not a revolution, core APIs are here to stay and released betas should be stable, after all the codebase is tested 😉 I would only advise to pin your redux-saga dep to an exact version and you should be ready to go (after reading our release notes)

**Comment by kamalkne** [comment]
Is anyone working on this issue? I am interested to work on it.

**Comment by restrry** [comment]
actually not. you are welcome, so feel free to get something from the list that doesn't have a link to PR

**Comment by SeregaSE** [comment]
Can i take retry effect?

**Comment by shinima** [comment]
@SeregaSE   Of course.

**Comment by SeregaSE** [comment]
could we say that retry is an effect?

**Comment by Andarist** [comment]
@SeregaSE yeah, smth like that, `retry` creates call effect descriptor that has that exact logic embedded in it, you dont have to go into such details while describing - you can look how i.e. `throttle` is described and do this one in a similar fashion

**Comment by SeregaSE** [comment]
After pull master in my local branch i have a trouble with push my changes

lerna ERR! npm run test exited 1 in 'babel-plugin-redux-saga'
lerna ERR! npm run test stderr:
FAIL test/runner.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

**Comment by restrry** [comment]
@SeregaSE 
I faced the same problem https://github.com/redux-saga/redux-saga/pull/1546,
jest already merged fix, wait for new version https://github.com/facebook/jest/pull/6792

**Comment by restrry** [comment]
closed as all points from PR title are done
